[package]
name = "rust_mp"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_mp"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }

[profile.release]
opt-level = 3
lto = true
